### ISSUE TITLE
how to use in ios

### ISSUE THREAD

**Issue by lany9527** [react-native-china/react-native-webkit-webview#4]
hi,  there is no example to explain how to use in ios ?

**Comment by Obooman** [comment]
Just use `WebView` component in iOS or use [react-native-wkwebview](https://github.com/CRAlpha/react-native-wkwebview) for your web pages, this repo aims at enhancing webview support for low version android systems.After Android 5 it uses chrome as webview supplier so there's no need to support.as [CrossWalk](https://www.crosswalk.com/), which library this project based on, has stopped because there's no need to maintain.
